chore(gh-action): push code snippets

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -62,3 +62,8 @@ jobs:
         TWINE_USERNAME: ${{ secrets.PYPI_USER }}
         TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
       run: twine upload --verbose dist/* || echo 'Version exists'
+
+    - name: Push code snippets to service-contracts
+      env:
+        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      run: sh ./scripts/deploy_code_snippets.sh || echo 'PR failed. There is probably nothing to commit'
