Ran yaml formatter on codebase

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -1,8 +1,9 @@
+---
 name: release
 
 on:
   push:
-    branches: [ master ]
+    branches: [master]
 
 jobs:
   lint:
@@ -26,68 +27,70 @@ jobs:
   test_core:
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v3
-    - uses: actions/setup-python@v4
-      with:
-        python-version: 3.8
+      - uses: actions/checkout@v3
+      - uses: actions/setup-python@v4
+        with:
+          python-version: 3.8
 
-    - name: Install required dependencies
-      run: |
-        python3 -m pip install --upgrade pip "poetry<1.2.0"
-        poetry config virtualenvs.create false
-        poetry install
+      - name: Install required dependencies
+        run: |
+          python3 -m pip install --upgrade pip "poetry<1.2.0"
+          poetry config virtualenvs.create false
+          poetry install
 
-    - name: Test core
-      env:
-        CI: 1
-      run: pytest tests/tests_unit -n8 --dist loadscope --maxfail 10 -m 'not dsl' --test-deps-only-core
+      - name: Test core
+        env:
+          CI: 1
+        run: pytest tests/tests_unit -n8 --dist loadscope --maxfail 10 -m 'not dsl'
+          --test-deps-only-core
 
   test_full_and_build_and_release:
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v3
-    - uses: actions/setup-python@v4
-      with:
-        python-version: 3.8
+      - uses: actions/checkout@v3
+      - uses: actions/setup-python@v4
+        with:
+          python-version: 3.8
 
-    - name: Install full dependencies
-      run: |
-        python3 -m pip install --upgrade pip "poetry<1.2.0"
-        poetry config virtualenvs.create false
-        poetry install -E all
+      - name: Install full dependencies
+        run: |
+          python3 -m pip install --upgrade pip "poetry<1.2.0"
+          poetry config virtualenvs.create false
+          poetry install -E all
 
-    - name: Test full
-      env:
-        LOGIN_FLOW: client_credentials
-        COGNITE_CLIENT_SECRET: ${{ secrets.COGNITE_CLIENT_SECRET }}
-        COGNITE_TOKEN_URL: https://login.microsoftonline.com/dff7763f-e2f5-4ffd-9b8a-4ba4bafba5ea/oauth2/v2.0/token
-        COGNITE_TOKEN_SCOPES: https://greenfield.cognitedata.com/.default
-        COGNITE_CLIENT_ID: 14fd282e-f77a-457d-add5-928ec2bcbf04
-        COGNITE_PROJECT: python-sdk-test
-        COGNITE_BASE_URL: https://greenfield.cognitedata.com
-        COGNITE_CLIENT_NAME: python-sdk-integration-tests
-        CI: 1
-      run: |
-        pytest tests --cov --cov-report xml:coverage.xml -n8 --dist loadscope --reruns 2
+      - name: Test full
+        env:
+          LOGIN_FLOW: client_credentials
+          COGNITE_CLIENT_SECRET: ${{ secrets.COGNITE_CLIENT_SECRET }}
+          COGNITE_TOKEN_URL: https://login.microsoftonline.com/dff7763f-e2f5-4ffd-9b8a-4ba4bafba5ea/oauth2/v2.0/token
+          COGNITE_TOKEN_SCOPES: https://greenfield.cognitedata.com/.default
+          COGNITE_CLIENT_ID: 14fd282e-f77a-457d-add5-928ec2bcbf04
+          COGNITE_PROJECT: python-sdk-test
+          COGNITE_BASE_URL: https://greenfield.cognitedata.com
+          COGNITE_CLIENT_NAME: python-sdk-integration-tests
+          CI: 1
+        run: |
+          pytest tests --cov --cov-report xml:coverage.xml -n8 --dist loadscope --reruns 2
 
-    - uses: codecov/codecov-action@v3
-      with:
-        token: ${{ secrets.CODECOV_TOKEN }}
-        file: ./coverage.xml
+      - uses: codecov/codecov-action@v3
+        with:
+          token: ${{ secrets.CODECOV_TOKEN }}
+          file: ./coverage.xml
 
-    - name: Build package
-      run: poetry build
+      - name: Build package
+        run: poetry build
 
-    - name: Build docs
-      run: cd docs && make html
+      - name: Build docs
+        run: cd docs && make html
 
-    - name: Release to PyPI
-      env:
-        TWINE_USERNAME: __token__
-        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
-      run: twine upload --verbose dist/* || echo 'Version exists'
+      - name: Release to PyPI
+        env:
+          TWINE_USERNAME: __token__
+          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
+        run: twine upload --verbose dist/* || echo 'Version exists'
 
-    - name: Push code snippets to service-contracts
-      env:
-        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      run: sh ./scripts/deploy_code_snippets.sh || echo 'PR failed. There is probably nothing to commit'
+      - name: Push code snippets to service-contracts
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: sh ./scripts/deploy_code_snippets.sh || echo 'PR failed. There is probably
+          nothing to commit'
